-- Table: public.meadowlogs

-- DROP TABLE public.meadowlogs;

CREATE TABLE public.meadowlogs
(
    logdata text COLLATE pg_catalog."default",
    meadowlogid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT meadowlogs_pkey PRIMARY KEY (meadowlogid)
)

TABLESPACE pg_default;

ALTER TABLE public.meadowlogs
    OWNER to careerme;
-- Index: IX_meadowlogs_meadowlogid

-- DROP INDEX public."IX_meadowlogs_meadowlogid";

CREATE INDEX "IX_meadowlogs_meadowlogid"
    ON public.meadowlogs USING btree
    (meadowlogid ASC NULLS LAST)
    TABLESPACE pg_default;